<?php

namespace AppBundle\Repository;

/**
 * ExchangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangeRepository extends \Doctrine\ORM\EntityRepository
{
}
