imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: "@SelCategoryBundle/Resources/config/services.yml" }
    - { resource: "@SelExchangeBundle/Resources/config/services.yml" }
    - { resource: "@SelFaqBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app_bundle.service.types:
        1: Offre
        2: Demande
        3: Offre Flash
        4: Demande Flash
    app_bundle.service.flash_types_ids:
        - 3 # This is a reference to app_bundle.service.types keys
        - 4
    app_bundle.service.domains:
        1: Service / savoir
        2: Preterie / donnerie

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "fr"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - LexikFormFilterBundle:Form:form_div_layout.html.twig
        - 'Form/form_div_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
    port:       "%mailer_port%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secured
    user_class: AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%main_email_address%"
        sender_name: "%site_name%"
    resetting:
        email:
            from_email:
                address: "%security_email_address%"
                sender_name: "%site_name%"
            template: Emails/user_password_reset.email.twig
    registration:
        confirmation:
            from_email:
                address: "%register_email_address%"
                sender_name: "%site_name%"
            template: Emails/user_confirmation.email.twig

liip_imagine:
    driver: imagick
    filter_sets:
        cache: ~
        service_thumb:
            quality: 75
            animated: true
            filters:
                relative_resize: { widen: 400 }
        service_thumb2x:
            quality: 75
            animated: true
            filters:
                relative_resize: { widen: 800 }
        user_thumb:
            quality: 75
            animated: true
            filters:
                thumbnail: { size: [80, 80], mode: outbound }
        user_thumb2x:
            quality: 75
            animated: true
            filters:
                thumbnail: { size: [160, 160], mode: outbound }
        user_full:
            quality: 75
            animated: true
            filters:
                thumbnail: { size: [150, 150], mode: outbound }
        user_full2x:
            quality: 75
            animated: true
            filters:
                thumbnail: { size: [300, 300], mode: outbound }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'Pagination/sliding.html.twig'     # sliding pagination controls template
        sortable: 'Pagination/sortable_link.html.twig'

ewz_recaptcha:
    public_key:  '%captcha_public_key%'
    private_key: '%captcha_private_key%'
    locale_key:  'fr'