# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    form.type.service:
        class: AppBundle\Form\ServiceType
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: form.type, alias: service_type }
    form.type.exchange:
        class: AppBundle\Form\ExchangeType
        arguments: ["@security.authorization_checker", "@security.token_storage"]
        tags:
            - { name: form.type, alias: exchange_type }
    app.service_voter:
        class: AppBundle\Security\ServiceVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    app.user_voter:
        class: AppBundle\Security\UserVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
