services:
    article.form.article:
        class: ArticleBundle\Form\ArticleType
        arguments: ["@seldocument.manager"]
        tags:
            - { name: form.type }
    article.repository.article:
        class: ArticleBundle\Entity\ArticleRepository
        factory: ['@doctrine', getRepository]